### ISSUE TITLE
Not working with Intel 6300 AGN

### ISSUE THREAD

**Issue by michael7795** [codebutler/firesheep#30]
For some reason, in options my wireless car, 6300 AGN, is not an option in the interface pull down. The only option is my Ethernet... What should I do?

**Comment by GregTheRick** [comment]
The same with Dell Wireless 1397 mini-card. It is in winPcap that it does not recognize it. I do not know how to solve it. Could anyone help?

**Comment by SWiT** [comment]
I can not get my "Dell Wireless 1505 Draft 802.11n WLAN Mini-Card" to work under Vista.  I only get "Microsoft" in the options menu.  I think it has a Broadcom BCM4328 as it's chipset.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!

**Comment by GregTheRick** [comment]
Hey. I understand, but I think it is a bug, of course not directly with firesheep, but it is a part of it since it (probably winPcap) does not recognizes the wireless driver/ wireless card.
Regards hunZeboo

P.S.: I am a web developer, so I would like to ask you what is your suggestion to make a safer web i.e.: How would you solve the authentication. ;)
