### ISSUE TITLE
Limited interface options

### ISSUE THREAD

**Issue by epotn** [codebutler/firesheep#38]
Preferences -> Capture (Interface) the only options I get are Microsoft, Ethernet Controller, and Microsoft again I am unable to see my Wireless card is there a fix ? and what is the Microsoft option? I am on an open network where I know people are logging onto facebook and other sites
thanks

**Comment by Maximus9** [comment]
I have the same problem. My options are the following: 
1. MS Tunnel Interface Driver
2. Gigabit Ethernet Controller
3. Microsoft....

Tried all of them but captures, yet :(

**Comment by jonlucc** [comment]
Same here.  The Microsoft interface captures all of my local sessions (on the same computer running firesheep).

**Comment by ebm-zz** [comment]
I am having the same problem not getting any data from other computers but my own.  I read somewhere that certain wireless card manufacturers may not allow "promiscuous monitoring mode" or at least they dont enable this in their driver.  I dont know if the winpcap software is supposed to enable this feature or not.  There arent any settings to be configured in it, anyway.  I have an acer aspire with Atheros wireless card and a Lenovo T400 with Intel 5100 wireless card.  Neither seem to allow promiscuous mode.

**Comment by jonlucc** [comment]
After reviewing this a bit further, it looks like WinPCap doesn't really support 802.11.  From their website:

Wireless adapters: these adapters may present problems, because they are not properly supported by the Windows Kernel. Some of them are not detected, other don't support promiscuous mode. In the best case, WinPcap is able to see an Ethernet emulation and not the real transiting packets: this means that the 802.11 frames are transformed into fake Ethernet frames before being captured, and that control frames are not received. 
http://www.winpcap.org/misc/faq.htm#Q-16

**Comment by msauers** [comment]
How is anyone getting this to work. I've tried four different laptops with a total of six different WiFi interfaces and none of them work. I see "Microsoft" and I see the LAN adapters, but Firesheep/WinPCap is completely failing to give me the ability to choose a WiFi adapter.

**Comment by codebutler** [comment]
There are two independent issues here:
1. Some people are only seeing "Microsoft" instead of the name of their wireless interface. This is only a problem with the name and nothing else. Wireshark appears to have the same problem.
2. Some wireless interfaces don't support promiscuous mode, so you'll only see your own traffic. If you're able to see your own traffic from a second web browser, then you've got the right interface selected.

**Comment by pisto** [comment]
"Microsoft" interface won't work. It's a virtual interface which provides a stripped-down version of the wireless frames (only up to the ethernet packet which is originally incapsulated in the wireless LAN frame), and filters out any packet which is not directed to the client: that is, you can't sniff other stations attached to the AP.
Monitor mode in Windows works only with a VERY limited subset of cards. You may check in this rather old list of drivers: http://www.aircrack-ng.org/doku.php?id=compatibility_drivers
