### ISSUE TITLE
How to: Firesheep on Windows 7 (video)

### ISSUE THREAD

**Issue by partridge** [codebutler/firesheep#49]
# Watch:

http://www.youtube.com/watch?v=AomuNpnZdLc
# Required:

Firesheep Extension
http://codebutler.github.com/firesheep/

WinPcap
http://www.winpcap.org/

Cain & Abel
http://www.oxid.it/cain.html

**Comment by ilovesurfing** [comment]
I can only manage to get "half routing". Is this possible to do on a college campus?

**Comment by ilovesurfing** [comment]
also, I look at the APR-HTTPS on the left hand side and for all of the entries it says 

"couldnt accept SSL connection from client"

It is definitely receiving packets, but I cant get it to work

**Comment by ilovesurfing** [comment]
Thanks for the help. Its a little tricky, but I got it to work. It still amazes me how with this firefox plugin, a double click assumes the users identity...

I am still getting half routing but it still works. I only pick up a few facebook accounts though so I assume half routing is the reason it wont pick up more. 

Also, my computer came with windows vista rather than 7. I now have win7, but is it still necessary to use cain and abel or is there another workaround? I guess winpcap just doesnt support my network card for promiscuous mode?

Thanks again for your time and help

**Comment by ilovesurfing** [comment]
did partridge get banned or something?

**Comment by partridge** [comment]
@ilovesurfing

Nope, just doing a little housecleaning, reformatting, etc. ;)

**Comment by binded-zz** [comment]
i must say i did this but with a few changes strange network but it works but with errors some times stuff like backend eixt 1 and dup page errors which seem to be script errors errors in getting users names but it works

**Comment by binded-zz** [comment]
lol btw i just notice that github is a site that is scanned :)

**Comment by funboy** [comment]
Can I get an invitation to watch the video? It's private.

**Comment by partridge** [comment]
@funboy

I put it back up. I was getting spammed and trolled like crazy and YouTube's new inline editor would not let me turn off comments for good. Now it seems like everything is working on YouTube's end.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
