### ISSUE TITLE
Syntax Error: JSON.parse (linux x86_64)

### ISSUE THREAD

**Issue by fedterzi** [codebutler/firesheep#81]
System: ubuntu linux maverick 10.10 x86_64 firefox 3.6.12
installed dependencies and make didn't throw any warning or error.
after installing, when trying to open preference pane, it throws the following error: http://img203.imageshack.us/img203/4237/schermatajf.png

Error console reports that an empty string has been passed to getElementById()

After that, preference pane opens but it doesn't show any interface, tried browsing to firesheep-backend and "sudo ./firesheep-backend --fix-permissions", then "./firesheep-backend mon0 tcp port 80" and it was displaying packets so it's not a backend error.

**Comment by Gijutsu** [comment]
This bug was introduced by commit 047b5ccdafce44a379d4, so you need to revert this commit in order to make it work or find and fix the bug itself. However an automatic revert with git fails and therefore you have to manually resolve the conflicts or do:
git rebase -i 2155daf9bd16cda89827
remove the commits 047b5ccdafce44a379d4 and a8205bba27f162573560

**Comment by fedterzi** [comment]
This worked. Thanks. Why no one reported the bug?

**Comment by Gijutsu** [comment]
Beats me. But you are more than welcome to try to fix the commit if you find the time :-)
